spring:
  jpa:
    database: mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JF1sh?useSSL=false
    username: root
    password: 267736yu
#rabbitmq基本配置
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
    publisher-confirms: true #采用消息确认模式 消息发送后异步等待 消息响应
    publisher-returns: true
    template:
      mandatory: true
    #rabbitmq消费端配置
    listener:
      simple:
       concurrency: 5 #并发最大连接池
       acknowledge-mode: manual #签收的模式 手动签收 auto自动签收
       max-concurrency: 10 #最大并发量
       prefetch: 1 #限流 同一时间只能有一条消息被消费端消费


#  mvc:
#    view:
#      prefix: /WEB-INf/jsp/
#      suffix: .jsp
##spring.datasource.url=jdbc:mysql://localhost:3306/prometheus
#spring.datasource.username=root
#spring.datasource.password=123
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.jpa.database=mysql
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=123
#spring.datasource.url=jdbc:mysql://localhost:3306/prometheus?useUnicode=true&characterEncoding=utf-8&useSSL=true
local:
  ip: 192.168.1.1
  port: 8080
  test: ssss

# jasypt 自定义密钥
jasypt:
  encryptor:
    password: panther
server:
  port: 8081
